#ifndef INC_7SCW_SHOW_ALL_STARTUP_H
#define INC_7SCW_SHOW_ALL_STARTUP_H

void startupMG_SHOW_ALL_STARTUP_1();
void startupMG_SHOW_ALL_STARTUP_2();
void SHOW_ALL_STARTUP();

#endif //INC_7SCW_SHOW_ALL_STARTUP_H